"""baseline pre-multi-user schema

Revision ID: 6c2cdc370222
Revises:
Create Date: 2026-06-06 20:22:24.243263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c2cdc370222"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "narrators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "styles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tropes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("original_publication_year", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("genres", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("moods", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "author_styles",
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("attribute_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["style_id"],
            ["styles.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "style_id", "attribute_type"),
    )
    op.create_table(
        "editions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("isbn_13", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("audio_minutes", sa.Integer(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "narrator_styles",
        sa.Column("narrator_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("attribute_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["narrator_id"],
            ["narrators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["style_id"],
            ["styles.id"],
        ),
        sa.PrimaryKeyConstraint("narrator_id", "style_id", "attribute_type"),
    )
    op.create_table(
        "suggestions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("suggested_at", sa.DateTime(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_contributors",
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("work_id", "author_id", "role"),
    )
    op.create_table(
        "work_styles",
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("attribute_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["style_id"],
            ["styles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("work_id", "style_id", "attribute_type"),
    )
    op.create_table(
        "work_tropes",
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("trope_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trope_id"],
            ["tropes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("work_id", "trope_id"),
    )
    op.create_table(
        "edition_narrators",
        sa.Column("edition_id", sa.UUID(), nullable=False),
        sa.Column("narrator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrator_id"],
            ["narrators.id"],
        ),
        sa.PrimaryKeyConstraint("edition_id", "narrator_id"),
    )
    op.create_table(
        "reading_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("edition_id", sa.UUID(), nullable=False),
        sa.Column("date_started", sa.Date(), nullable=True),
        sa.Column("date_completed", sa.Date(), nullable=False),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reading_history")
    op.drop_table("edition_narrators")
    op.drop_table("work_tropes")
    op.drop_table("work_styles")
    op.drop_table("work_contributors")
    op.drop_table("suggestions")
    op.drop_table("narrator_styles")
    op.drop_table("editions")
    op.drop_table("author_styles")
    op.drop_table("works")
    op.drop_table("tropes")
    op.drop_table("styles")
    op.drop_table("narrators")
    op.drop_table("authors")
    # ### end Alembic commands ###
