"""Library-directory search over a committed static snapshot.

WHY a snapshot: OverDrive's Thunder `/v2/libraries` endpoint ignores its `query` param — it always
returns the same full ~13k-library list — and Libby's real autocomplete host is gated. So live name
search is impossible there. Instead we ship `library_directory.json` ({slug, name}, regenerated by
`scripts/fetch_library_directory.py`) and filter it here. Filtering ~13k strings is instant; the only
cost is regenerating the snapshot, which is a rare offline action (the directory is near-static).

See ADR in docs/project_notes/decisions.md. The live-fetch + cache alternative is tracked as a GitHub
enhancement issue."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_SNAPSHOT = Path(__file__).resolve().parent / "library_directory.json"
_DEFAULT_LIMIT = 25


@lru_cache(maxsize=1)
def _directory() -> list[dict]:
    """Load the snapshot once per process. Each record is {"slug", "name"}."""
    with _SNAPSHOT.open(encoding="utf-8") as f:
        return json.load(f)


def search(query: str, limit: int = _DEFAULT_LIMIT) -> list[dict]:
    """Case-insensitive substring search over the snapshot, ranked so prefix matches come first
    (a library typed as 'seattle' should surface 'Seattle…' above 'North Seattle…'), then by name.
    Returns up to `limit` records [{"slug", "name"}]. Blank query → []."""
    q = query.strip().lower()
    if not q:
        return []
    prefix: list[dict] = []
    contains: list[dict] = []
    for rec in _directory():
        name_l = rec["name"].lower()
        if name_l.startswith(q):
            prefix.append(rec)
        elif q in name_l:
            contains.append(rec)
    prefix.sort(key=lambda r: r["name"].lower())
    contains.sort(key=lambda r: r["name"].lower())
    return (prefix + contains)[:limit]
