"""Alembic environment (Lift 1, ADR-048). URL resolution is shared with the app via
db/session.resolve_database_url so migrations always target the same database."""

from logging.config import fileConfig

from agentic_librarian.db.models import Base
from agentic_librarian.db.session import resolve_database_url
from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import create_engine

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _url() -> str:
    # Tests/conftest inject via Config.set_main_option("sqlalchemy.url", ...);
    # otherwise resolve exactly like the app (DATABASE_URL first).
    return config.get_main_option("sqlalchemy.url") or resolve_database_url()


def render_item(type_, obj, autogen_context):
    """Render pgvector columns with the right import in autogenerated migrations
    (the standard pgvector+alembic recipe; without this, autogenerate emits an
    unimportable type path)."""
    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})"
    return False


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_url())
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata, render_item=render_item)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
